export type Area = 'Seleccione un area' | 'Comedor' | 'Oficina' | 'Taller' | 'Terreno';

export const opcionesArea: Area[] = [
    "Seleccione un area",
    "Comedor",
    "Oficina",
    "Taller",
    "Terreno",
];

export const opcionesProceso: Record<Area, string[]> = {
  "Seleccione un area": [],
  Taller: [
    "Construcción y reparación de carrozados",
    "Mantención vehiculos CODE",
    "Mantención Motobombas",
    "Mantención sistema de espuma",
    "Mantención sistema de retardante",
    "Instalación Bases de Cargulo",
    "Trabajos con equipos energizados",
  ],
  Oficina: [
    "Estadía en oficina",
    "Trabajos administrativos",
    "Tránsito en oficinas",
    "Factores de Riesgos Psicosociales",
    "Traslado a oficina desde su casa y viceversa",
  ],
  Comedor: [
    "Alimentación",
    "Calefacción",
  ],
  Terreno: [
    "Control de incendios",
    "Desplazamiento a taller",
    "Operación de móviles en terreno",
    "Trabajos en terreno",
    "Traslado de elementos pesados",
  ],
};

export const opcionesActividad: Record<Area, string[]> = {
  "Seleccione un area": [],
  Taller: [
    "Armado y desarrollo de motobombas",
    "Armado y desarrollo de partes y piezas del monitor",
    "Armado y desarrollo de partes y piezas del sistema de espuma",
    "Ingreso a taller desde oficina",
    "Levantamiento de cargas",
    "Limpieza de partes de equipos (válvulas, cañerias, filtros)",
    "Limpieza estanque de retardante",
    "Recepción traspaso de vehículo PC-CODE",
    "Soldar al arco, MIG, TIG",
    "Trabajos de Montajes",
    "Trabajos de Soldadura",
    "Uso y Mantención de equipos y herramientas",
  ],
  Oficina: [
    "Digitación, Uso de Computador",
    "Desplazamiento dentro de oficinas",
    "Trabajos en oficina",
    "Uso de útiles de oficina",
    "Apoyo social en la empresa y calidad de liderazgo",
    "Trabajo y desarrollo de habilidades",
  ],
  Comedor: [
    "Calentar comida en microondas",
    "Ingesta de alimentos contraindicados por problemas de salud",
    "Uso de estufa para calefacción",
  ],
  Terreno: [
    "Almacenamiento de herramientas y equipos en cajuela del móvil",
    "Apoyo en la estructura del móvil con la puerta abierta",
    "Ascenso y descenso desde un móvil",
    "Cambio de neumáticos",
    "Combate de incendios",
    "Conducción",
    "Desplazamiento en locomoción propia, colectiva y//o a pie",
    "Encendido de prueba de maquinarias y equipos",
    "Estacionamiento en lugares particulares",
    "Fumigación (Desinsectación - Desratización) en instalaciones",
    "Uso de energía eléctrica",
  ],
};

export const opcionesPeligro: Record<Area, string[]> = {
  "Seleccione un area": [],
  Comedor: [
    "Ingesta de alimentos contraindicados",
    "Contacto con elementos calientes al consumir o manipular",
    "Caídas al subir/bajar del móvil",
    "Contacto con estufa",
    "Caídas por desplazamiento en superficies de trabajo",
    "Contacto con fuego por incendio estructural",
    "Inhalación o contacto con producto químico",
    "Exposición a monóxido de carbono",
    "Contacto con objetos cortantes",
    "Atrapamiento de manos y golpes",
    "Incendio por fumar en zonas prohibidas",
    "Exposición a ruido",
    "Disminución física por movimientos repetitivos",
    "Contacto con combustibles/lubricantes",
    "Exceso de carga de trabajo",
    "Entorno desagradable",
    "Mal trato a clientes",
    "Violencia de clientes",
    "Instalaciones sin condiciones mínimas",
    "Falta de pagos regulares",
    "Falta de planificación laboral",
    "Falta de adaptación horaria",
    "No optimizar horarios por responsabilidades familiares",
  ],
  Oficina: [
    "Movimiento repetitivo por uso de computador",
    "Movimiento repetitivo por uso de mouse",
    "Postura forzada por utilización de escritorio y/o silla inadecuada",
    "Uso de pantallas de computador",
    "Caídas a un mismo nivel",
    "Contacto con artefactos o circuitos eléctricos",
    "Contacto con elementos cortantes",
    "Sobreesfuerzo por manejo manual de cargas",
    "Exposición a ruido",
    "Deficiente planificación",
    "Demanda excesiva de asignación",
    "Falta de apoyo de supervisores",
    "Falta de escucha por parte de gerencia",
    "Falta de definición de perfil de cargo",
    "Falta de participación en mejoras",
    "Falta de desarrollo en competencias",
    "Falta de tareas alternativas",
    "Falta de reuniones periódicas",
    "Falta de información sobre cambios",
    "Falta de mecanismos éticos",
    "Discriminación e injusticia",
    "No respetar confidencialidad",
    "Falta de prevención del estrés",
    "Falta de comunicación informal",
    "Falta de modelo de relaciones de apoyo",
    "Falta de visita regular de gerencias",
    "Falta de frecuencia comunicacional",
    "Falta de programa de ayuda mutua",
    "Falta de actividades sociales",
    "Falta de formación en respeto",
    "Falta de procedimientos de elogio",
    "Falta de reporte de desempeño",
    "Falta de expresión emocional",
    "Falta de contrato claro",
    "Falta de política de equidad",
  ],
  Taller: [
    "Ingreso a taller cercano a herramientas en operación",
    "Contacto con elementos corto punzantes (soldadura)",
    "Tránsito por sectores no habilitados (soldadura)",
    "Trabajos sobre andamios o caballetes (soldadura)",
    "Caídas por terrenos irregulares (soldadura)",
    "Lesiones por deficiente planificación (soldadura)",
    "Uso de EPP defectuoso (soldadura)",
    "Exposición a fuego y material incandescente",
    "Sobreesfuerzo por manejo de materiales (soldadura)",
    "Contacto con elementos corto punzantes (montajes)",
    "Tránsito por sectores no habilitados (montajes)",
    "Trabajos sobre andamios o caballetes (montajes)",
    "Caídas por terrenos irregulares (montajes)",
    "Lesiones por deficiente planificación (montajes)",
    "Uso de EPP defectuoso (montajes)",
    "Sobreesfuerzo por manejo de materiales (montajes)",
    "Caídas en taller",
    "Golpeado por caída de herramientas (recepción vehículo)",
    "Contacto con químicos (recepción vehículo)",
    "Golpeado por cierre de compuerta",
    "Caídas al mismo nivel en inspección",
    "Caídas al subir/bajar del móvil (recepción)",
    "Golpeado por o contacto con objetos calientes, cortantes",
    "Emisión de chispas",
    "Contacto con químicos (espuma)",
    "Circuitos energizados (espuma)",
    "Contacto con químicos (retardante)",
    "Circuitos energizados (retardante)",
    "Contacto con químicos (monitor CODE)",
    "Circuitos energizados (monitor CODE)",
    "Contacto con químicos (motobombas)",
    "Circuitos energizados (motobombas)",
    "Posturas no ergonómicas (espuma)",
    "Posturas no ergonómicas (retardante)",
    "Posturas no ergonómicas (monitor CODE)",
    "Posturas no ergonómicas (motobombas)",
    "Atrapamiento de manos (espuma)",
    "Atrapamiento de manos (retardante)",
    "Atrapamiento de manos (monitor CODE)",
    "Atrapamiento de manos (motobombas)",
  ],
  Terreno: [
    "Choque, colisión, volcamiento, atropello, asaltos, agresión de terceros",
    "Colisión en predios forestales",
    "Caída de ramas sobre vehículo",
    "Volcamiento por caminos angostos",
    "Conducción con condiciones de salud deficientes",
    "Volcamiento por cruce de animales",
    "Volcamiento por trayectos largos",
    "Conducir sin cinturón de seguridad",
    "Intervención de terceros",
    "Conducción con distractores",
    "Actividades a orilla de carretera",
    "No atento a condiciones de tránsito",
    "Exceso de velocidad",
    "Puentes con fallas estructurales",
    "Golpeado por compuerta de cajuela",
    "Golpeado por cambio de neumáticos",
    "Agresión en lugares particulares",
    "Contacto con calor o cierre del móvil",
    "Caída al bajar escala",
    "Exposición a partículas (incendios)",
    "EPP en mal estado (incendios)",
    "Desmayo o síncope por deshidratación",
    "Exposición a radiación solar",
    "Falta de involucramiento",
    "Falta de libertad o control excesivo",
    "No abordar problemas inmediatamente",
    "No identificar fuentes externas de apoyo",
    "Falta de procedimientos de ayuda",
    "Falta de estrategia preventiva de comportamientos ofensivos",
    "Falta de procedimientos ante violencia",
    "No intervenir en casos ofensivos",
  ],
};

export const opcionesAgenteMaterial: Record<Area, string[]> = {
  "Seleccione un area": [],
  Taller: [
    "Herramientas y equipos",
    "Inherente a herramientas y equipos",
    "Inherente a máquinas, herramientas y equipos",
    "Inherente a materiales",
    "Inherente a productos o sustancias peligrosas",
    "Máquinas, herramientas y equipos",
    "Instalaciones",
    "Personas",
  ],
  Oficina: [
    "Equipo",
    "Inherente a equipos",
    "Instalaciones",
    "Personas",
  ],
  Comedor: [
    "Instalaciones",
    "Equipo",
    "Personas",
    "Inherente a productos o sustancias peligrosas",
  ],
  Terreno: [
    "Vehículos",
    "Arboles",
    "Herramientas y equipos",
    "Inherente a materiales, herramientas y equipos",
    "Inherente a productos o sustancias peligrosas",
    "Personas",
  ],
};

export const opcionesRiesgo = [
    "Aceptable",
    "Importante",
    "Intolerable",
    "Moderado",
];

export const opcionesMedidas = [
    "Conducir de acuerdo con la normativa Ley N° 18290",
    "Maneje a la defensiva",
    "Respetar señalizaciones",
    "Utilizar cinturón de seguridad",
    "Dar cumplimiento a procedimiento de uso de vehículos",
    "Control por GPS en vehículos empresa y arrendados",
    "Realizar pausas activas",
    "Ejercicios compensatorios",
    "No superar los límites de carga según ley 20.001",
    "Usar técnica de levantamiento: rodillas flexionadas y espalda recta",
    "Solicitar ayuda si la carga supera los 25 kg",
    "Utilizar elementos de apoyo mecánico",
    "No trabajar con artefactos o circuitos energizados",
    "Usar mascarilla con doble filtro",
    "Usar guantes de Nitrilo",
    "Cumplir Plan de Emergencia",
    "Mantener distancia mínima de seguridad (3m en talleres)",
    "No ingresar sin elementos de seguridad",
    "Apagar microondas antes de retirar envase",
    "Utilizar papel/toalla para manipular objetos calientes",
    "Consumo de alimentos en buen estado",
    "Uso obligatorio de arnés",
    "Verificar estado de andamios/caballetes",
    "Uso de EPP para soldador: chaqueta, pantalón, máscara facial, polainas",
    "No transportar herramientas filosas en la ropa",
    "Uso de protección auditiva: fono/tapón",
    "Uso de biombos de atenuación de ruido",
    "No correr",
    "No transitar con las manos en los bolsillos",
    "Inspeccionar EPP diariamente",
    "Informar deterioro de herramientas",
    "No apoyarse en zonas calientes o de cierre",
    "Utilizar tres puntos de apoyo al subir/bajar de móviles",
    "No discutir con terceros agresivos; buscar lugar seguro",
    "Informar fuga de químicos o combustibles",
    "Contener derrames si corresponde",
    "Mantener los envases cerrados",
    "No fumar fuera de zonas habilitadas",
    "Aplicar medidas del Protocolo UV: bloqueador, ropa larga",
    "Control de entrada y programas de prevención de violencia laboral",
];